---
title: "Copying the good"
description: |
  A short description of the post.
author:
  - name: Joshua Kunst
    url: http://jkunst.com/
date: 08-25-2020
output:
  distill::distill_article:
    self_contained: false
draft: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# source(here::here("_R/blog_setup.R"))
```

_Post updated on `r format(Sys.time(), '%b %d, %Y')`_

## Introducction

https://twitter.com/moritz_stefaner/status/1295733715579088896


```{r}
# remotes::install_github("rivaquiroga/guaguas")
library(babynames)
library(dplyr)
library(highcharter)

NAMES <- "Whitney"
# c("Anna",  "Britney", "Whitney")

data <- babynames::babynames %>% 
  filter(name %in% NAMES) %>% 
  select(name, x = year, y = prop) %>% 
  group_by(name, x) %>% 
  summarise(y = sum(y), .groups = "drop") %>% 
  select(x, y)

data
```

Color is given by the year -not the y value- so we'll create a function
to map colors from year values.

```{r}
pal <- col_numeric(viridisLite::inferno(100, begin = 0.2, end = 0.8), domain = NULL)

scales::show_col(pal(1:10))

data <- data %>% 
  mutate(
    color = pal(x),
    alpha = scales::rescale(sqrt(y), to = c(0.10, .75)),
    alpha = round(alpha, 2),
    color = purrr::map2_chr(color, alpha, shades::opacity)
  )

data

zns <- data %>% 
  select(value = x, color) %>% 
  # this will be needed when we have more years (more names)
  distinct(value, .keep_all = TRUE) %>% 
  list_parse()

data <- data %>% 
  select(x, y) %>% 
  mutate_all(round, 5)

data
```


```{r, layout="l-page"}
annotation <- data %>% 
  filter(y == max(y)) %>% 
  head(1) %>% # ties
  mutate(text = "&#9660;") %>% 
  df_to_annotations_labels()

highchart() %>%
  hc_add_series(
    data,
    "areaspline",
    hcaes(x, y),
    zones = zns,
    enableMouseTracking = FALSE,
    linkedTo = "serie"
  ) %>%
  hc_add_series(
    data,
    "spline",
    hcaes(x, y),
    color = "white",
    lineWidth = 8,
    hcaes(x, y),
    enableMouseTracking = FALSE,
    linkedTo = "serie"
  ) %>%
    hc_add_series(
    data,
    "spline",
    hcaes(x, y),
    zones = zns,
    lineWidth = 4,
    id = "serie",
    name = NAMES
  ) %>%
  hc_plotOptions(
    series = list(
      showInLegend = FALSE,
      zoneAxis = "x",
      marker = list(enabled = FALSE),
      hover = list(halo = list(size = 0))
    )
  ) %>% 
  hc_yAxis(visible = FALSE) %>% 
  hc_xAxis(
    lineColor = "transparent",
    tickLength = 0,
    tickInterval = 1,
    labels = list(
      style = list(color = "gray"),
      useHTML = TRUE,
      formatter = JS("function(){  var v = (this.value % 5 == 0) ? '<span>&#9679</span>' : '•';  return v; }")
    )
  ) %>% 
   hc_annotations(
     list(
       draggable = "",
       labelOptions = list(
         shape = "connector",
         y = -30,
         verticalAlign = "top",
         justify = FALSE,
         crop = TRUE,
         useHTML = TRUE,
         style = list(fontSize = "0.8em", textOutline = "1px white")
         ),
       labels = annotation
       )
     ) %>% 
  hc_size(height = 300)
```

