---
title: "U2 360º World Tour"
description: |
  A short description of the post.
author:
  - name: Joshua Kunst
    url: http://jkunst.com/
date: 04-10-2019
output:
  distill::distill_article:
    self_contained: true
    toc: true
categories: 
  - data-visualization
  - highcharts    
editor_options: 
  chunk_output_type: console
preview: images/preview.png
draft: true
---

```{r setup, include=FALSE}
source(here::here("_R/blog_setup.R"))
```

## intro

```{r, results='hide'}
library(tidyverse)
library(rvest)
library(lubridate)
Sys.setlocale("LC_TIME","English")
```


```{r}
html <- read_html("https://en.wikipedia.org/wiki/U2_360%C2%B0_Tour")

html_data <- html_table(html, fill = TRUE)[[2]] 

html_data <- html_data %>% 
  tbl_df() %>% 
  rename_all(str_to_lower) %>% 
  rename_all(str_replace_all, "\\s+", "_")

glimpse(html_data)

data <- html_data %>%
  mutate(leg = ifelse(str_detect(date, "Leg "), date, NA)) %>% 
  fill(leg) %>% 
  filter(!str_detect(date, "Leg "), date != "TOTAL") %>% 
  mutate(
    leg = str_replace(leg, " — ", ": "),
    attendance = str_extract(attendance, ".* "),
    attendance = str_replace_all(attendance, ",| |/", ""),
    attendance = as.numeric(attendance),
    revenue =  str_replace_all(revenue, ",|\\$", ""),
    revenue = as.numeric(revenue),
    revenue = coalesce(revenue, 0),
    date = as.Date(date, format = "%d %B %Y"),
    leg = str_replace(leg, "\\[\\d+\\]\\[\\d+\\]", ""),
    location = paste0(country, ", ", city)
    )

# summarise(data, sum(revenue))

data <- data %>% 
  group_by(leg, country, city, location, opening_act) %>% 
  mutate(revenue = mean(revenue, na.rm = TRUE)) %>% 
  ungroup()
```

Locations


```{r, cache=TRUE}
locations <- data %>% 
  distinct(location) %>% 
  pull()

gcodes <- map_df(locations, function(x = "United States, Minneapolis"){
  
  message(x)  

  response <- httr::GET(
    "http://www.datasciencetoolkit.org/maps/api/geocode/json",
    query = list(sensor = "false", address = x)
    ) %>% 
    httr::content()
  
  loc <- response$results[[1]]$geometry$location
  
  tibble(lat = loc[[1]], lon = loc[[2]])
  
}) 

gcodes <- gcodes %>% 
  mutate(location = locations)

data <- left_join(data, gcodes, by = "location")
```

```{r, echo=FALSE}
rmarkdown::paged_table(data)
```

## Getting a map

```{r}
library(ggmap) # you need also the maps package

world <- map_data("world")

ggplot() +
  geom_path(data = world, aes(long, lat, group = group)) 
```

I like have ugly charts at the beggining. We can make it better doing:

- Removing the Antartica
- Changing the projection. PLEASE. (https://gis.stackexchange.com/questions/44387/use-proj4-to-specify-robinson-projection-with-r-ggmap-and-ggplot2-packages)
- removing axis and add some dark colors

```{r}
library(ggalt)

world <- world %>%
  as_tibble() %>% 
  filter(region != "Antarctica")

p <- ggplot() +
  geom_polygon(
    data = world,
    aes(long, lat, group = group),
    color = "gray20", fill = "gray10",
    size = 0.25
    ) +
  coord_proj("+proj=robin +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs") +
  theme_void() +
  theme(
    legend.position = "none",
    panel.background = element_rect(fill = "black")
    )

p
```

> Oh look! There is New Zealand!

## Animate!

```{r}
library(gganimate)

data <- data %>%
  mutate(
    id = row_number(),
    attendance_cum_format = scales::comma(cumsum(attendance)),
    revenue_cum_format = scales::dollar(cumsum(revenue)),
    events = 1,
    events = cumsum(events),
    text = str_c(
      leg,
      location,
      str_c("Events: ", events),
      str_c("Attendace: ", attendance_cum_format),
      str_c("Revenue: ", revenue_cum_format),
      sep = "\n"
      )
    ) %>% 
  group_by(leg) %>% 
  mutate(
    xmin = min(lat),
    xmax = max(lat),
    ymin = min(lon),
    ymax = max(lon)
    ) %>% 
  ungroup() %>% 
  mutate(
    xmin_cum = RcppRoll::roll_min(xmin),
    xmax_cum = RcppRoll::roll_max(xmin),
    ymin_cum = RcppRoll::roll_min(xmin),
    ymax_cum = RcppRoll::roll_max(xmin),
  )

dtest <- sample_n(data, 20) %>% arrange(date)

p <- ggplot(dtest) +
  geom_polygon(
    data = world,
    aes(long, lat, group = group),
    color = "gray20", fill = "gray10",
    size = 0.25
    ) +
  coord_proj("+proj=robin +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs") +
  theme_void() +
  theme(
    legend.position = "none",
    plot.background = element_rect(fill = "black"),
    title = element_text(color = "gray")
    ) +
  geom_point(
    aes(lat, lon, size = revenue, group = id),
    color = "gray",
    alpha = 0.5
    ) +
  geom_text(aes(label = text), x = 180 , y = 50, color = "white", size = 3, alpha = 0.5, hjust = 1)

p

a <- p + 
  transition_reveal(date) +
  enter_grow() 
  
a


p <- ggplot(dtest) +
  geom_polygon(
    data = world,
    aes(long, lat, group = group),
    color = "gray20", fill = "gray10",
    size = 0.25
    ) +
  coord_proj("+proj=robin +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs") +
  theme_void() +
  theme(
    legend.position = "none",
    plot.background = element_rect(fill = "black"),
    title = element_text(color = "gray")
    ) +
  geom_point(
    aes(lat, lon, size = revenue, group = id),
    color = "gray",
    alpha = 0.5
    ) +
  geom_text(aes(label = text, x = xmax * 1.10, y = ymax), color = "white", size = 2, alpha = 0.5, hjust = 1)

p

a <- p + 
  transition_reveal(date) +
  enter_grow() +
  view_zoom_manual(
    xmin = dtest$xmin-50,
    xmax = dtest$xmax+50,
    ymin = dtest$ymin-50,
    ymax = dtest$ymax+50
    )

a

animate(a, fps = 30, duration = 20, height = 588, width = 936)
```

